#!/usr/bin/bash
#SBATCH --job-name="spearman"
#SBATCH --nodelist=node242
#SBATCH --cpus-per-task=22
#SBATCH --time=80:00:00
#SBATCH --partition=ivm
#SBATCH --output=../../python_%j.out
#SBATCH --error=../../python_%j.err

./start.sh ../requirements.txt ./find_precursors.py 21 $HOME/processed $HOME/clusters $HOME/correlation_roll_spearman
# ./start.sh requirements.txt test_script.py NPARPROCS DIRECTORIES (can be many)
