#!/usr/bin/bash
#SBATCH --job-name="prec"
#SBATCH --nodelist=node240
#SBATCH --cpus-per-task=32
#SBATCH --time=50:00:00
#SBATCH --partition=ivm
#SBATCH --output=../../python_%j.out
#SBATCH --error=../../python_%j.err

./start.sh ../requirements.txt ./find_precursors.py 31 $HOME/processed $HOME/clusters $HOME/correlation
# ./start.sh requirements.txt test_script.py NPARPROCS DIRECTORIES (can be many)
